language: node_js
node_js:
  - '10'
  - '12'
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: yarn test
after_script: greenkeeper-lockfile-upload
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  skip_cleanup: true
  on:
    tags: true
    repo: lifeomic/eslint-plugin-typescript
    node: '10'
